### PR TITLE
Setup all of the HoH clusters in one VM

### PR DESCRIPTION
**Pull request by yanmxa**
Signed-off-by: myan <myan@redhat.com>

### CODE REVIEW

**Comment by yanmxa** [comment]
@clyang82 @morvencao /cc

**Comment by clyang82** [comment]
@yanmxa Please check the latest structure. I have modify the main branch. You can put your code into `cicd-scripts` folder. Thanks.

**Comment by yanmxa** [comment]
> @yanmxa Please check the latest structure. I have modify the main branch. You can put your code into `cicd-scripts` folder. Thanks.

Got it.

**Pull request closed without merging**
