### PR TITLE
update hoh lease with hoh agent.

### PR DESCRIPTION
**Pull request by morvencao**
ref: https://github.com/stolostron/backlog/issues/24609

Signed-off-by: morvencao <lcao@redhat.com>

### CODE REVIEW

**Comment by morvencao** [comment]
e2e failed because hoh agent permission don't changed in hoh-addon repo, created another PR for this https://github.com/stolostron/hub-of-hubs-addon/pull/25

**Comment by clyang82** [comment]
@morvencao You have 4 code smell. Let us fix them before merging.

**Pull request merged**
